### ISSUE TITLE
Header bar in the save/load UI is not stretching full-size.

### ISSUE THREAD

**Issue by xNicklaj** [fayaz12g/totk-aar#13]
In the save/load UI, while the bottom bar stretches though the whole wide resolution, the the upper bar doesn't, at least for 21:9.

**Comment by fayaz12g** [comment]
Fixed in 5.2.2

**Comment by xNicklaj** [comment]
![image](https://github.com/fayaz12g/totk-aar/assets/40305701/a37954ae-e43a-48e1-bbe2-d732e040e831)

I still have this issue

**Comment by fayaz12g** [comment]
I see, I misunderstood the original issue. I will look into it sometime this week

**Comment by Fruithapje21** [comment]
This issue has been fixed in v2.2.0 of TOTK-Ultrawide

**Comment by fayaz12g** [comment]
Fixed in 7.0.0
