### ISSUE TITLE
Gets stuck at Patching BLYT

### ISSUE THREAD

**Issue by AkiVonAkira** [fayaz12g/totk-aar#6]
3.1.0 Seems to get stuck at Patching BLYT for me, I have given it ample time and re run it a couple times. 
Python is correctly installed.

![image](https://github.com/fayaz12g/totk-aar/assets/113895247/cc1796b7-36c1-4501-b998-1f5fe138d02c)

**Comment by ryderhicks** [comment]
Seconding this. Was also having issues in 2.x, haven't been able to install successfully yet.

**Comment by fayaz12g** [comment]
Version 3.1.0 was very bugged. I have deleted it as the new gui incorporated issues. Please try v3.0.0

**Comment by ryderhicks** [comment]
Same issue.

```
Exception in Tkinter callback
Traceback (most recent call last):
  File "tkinter\__init__.py", line 1948, in __call__
  File "bGUI.py", line 139, in create_patch
FileNotFoundError: [WinError 3] The system cannot find the path specified: 'C:/Users/User/AppData/Roaming/yuzu/load/0100F2C0115B6000\\AAR MOD\\temp\\Common.Product.110.Nin_NX_NVN.blarc'
```

**Comment by fayaz12g** [comment]
I will look into this more when I’m home, it’s very odd as so far only 2-3 people encounter this error with Python installed from the Microsoft store and v3.

**Comment by fayaz12g** [comment]
Issue is fixed in the new v3.1 and python 3.11. Future version will not require python

**Comment by greensad** [comment]
Still getting stuck at "Patching BLYT" on v3.3.0. Tried deleting old py installs, repairing my current install, restarted several times.

**Comment by fayaz12g** [comment]
Please try the latest version if you can

**Comment by ryderhicks** [comment]
Happy to report the issue is resolved for me, and the mod works flawlessly. Thanks for your work, @fayaz12g
